name: Build and Release Electron App

# Trigger the workflow only when a tag is pushed
on:
  push:
    tags:
      - 'v*.*.*'  # This pattern matches version tags like v1.0.0, v2.3.1, etc.

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Ensure Node.js 20 is installed

      # Step 3: Install npm dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the Electron app
      - name: Build the Electron app
        run: npm run build

      # Step 5: Package the Electron app using electron-builder without publishing
      - name: Package Electron app
        run: |
          npx electron-builder --linux --publish never  # Ubuntu build
          npx electron-builder --win --publish never    # Windows build
          npx electron-builder --mac --publish never    # macOS build

      # Step 6: Upload the build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: WaveFlexIntegrator-${{ matrix.os }}
          path: dist/

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Download all build artifacts
      - name: Download Ubuntu artifact
        uses: actions/download-artifact@v3
        with:
          name: WaveFlexIntegrator-ubuntu-latest
          path: dist/ubuntu

      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: WaveFlexIntegrator-windows-latest
          path: dist/windows

      - name: Download macOS artifact
        uses: actions/download-artifact@v3
        with:
          name: WaveFlexIntegrator-macos-latest
          path: dist/macos

      # Step 2: Create GitHub release and upload the build artifacts
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/ubuntu/**/*.AppImage
            dist/windows/**/*.exe
            dist/macos/**/*.dmg
          generate_release_notes: true  # Automatically generate release notes based on commits and PRs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
